### ISSUE TITLE
Fallback architecture

### ISSUE THREAD

**Issue by isuruf** [archspec/archspec#11]
Let me know if this is not the correct place and I'll open an issue or send an email to the correct place.

If the host has features `A, B, C` and archspec only knows archs which have features `A, B` and `A, C`, then how does archspec select the architecture?

**Comment by isuruf** [comment]
Current code gives a preference to architectures with more ancestors https://github.com/archspec/archspec/blob/6fbf84f01137584f47f817457cd3187bf67eb8ef/archspec/cpu/detect.py#L195

Clang and GCC have their own total ordering schemes for x86 used for function multi-versioning. Would you be interested in adding these?

**Comment by alalazo** [comment]
> Current code gives a preference to architectures with more ancestors

True. This is because with the uarchs currently modeled it's a good enough heuristic.

> Clang and GCC have their own total ordering schemes for x86 used for function multi-versioning. Would you be interested in adding these?

I would certainly be interested in having a look at that, can you post some links here (or I'll look at LLVM / GCC sources myself asap :slightly_smiling_face: )?

**Comment by isuruf** [comment]
For clang, they use a bit mask depending on the flags enabled. See https://reviews.llvm.org/D47474
GCC has a more complicated ordering based on the features enabled and the processor type, https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/i386-builtins.c#L1829-L1864

**Comment by isuruf** [comment]
We can add a field like,
```
ordering:
   gcc: value
   clang: value
   spack: value
```
for the 3 different schemes and the user will be able to use whichever ordering scheme they like.

**Comment by isuruf** [comment]
Anything I can do to help? I'd like to add this to conda package manager.

**Comment by alalazo** [comment]
Apologies for the lack of reply, been a bit busy lately. I still need to check how complicated LLVM and GCC selection mechanisms are, but in general I would be more for employing the "Fundamental Theorem of Software Engineering" (solve a problem with a layer of indirection). This means that if we decide that different selection mechanisms are needed I would:

1. Implement a default one that comes with the library and requires no user intervention
2. Document the API to insert a custom selection mechanism from client code

Would that fit with your case? Also, do you have examples where the current behavior for `x86_64` is different from `gcc` or `clang`?

**Comment by isuruf** [comment]
> Would that fit with your case? 

Yes.

> Also, do you have examples where the current behavior for x86_64 is different from gcc or clang?

Not yet, but I have another use case where this is useful.

For eg: if I build binaries for `nocona, ivybridge, broadwell` only, I need a way to figure out which one of them is the best for my platform. As far as I can see, there's no such API yet.

**Comment by alalazo** [comment]
To do that you can simply cycle:
```python
available_binaries = ...
for best_available in itertools.chain([current_target], current_target.ancestors):
    if best_available in available_binaries:
        break
```
since ancestors are ordered. We do something similar in Spack to warn users that their compiler is too old to optimize for their host architecture:
```console
$ spack arch
linux-ubuntu18.04-broadwell

$ spack spec zlib%gcc@4.8
Input spec
--------------------------------
zlib%gcc@4.8

Concretized
--------------------------------
==> Warning: gcc@4.8 cannot build optimized binaries for "broadwell". Using best target possible: "haswell"
zlib@1.2.11%gcc@4.8+optimize+pic+shared arch=linux-ubuntu18.04-haswell
```
The code that deals with that part is [here](https://github.com/spack/spack/blob/06f3381dfd4355939350a6f20004fcebe3a25d24/lib/spack/spack/concretize.py#L559-L580). In any case I would distinguish two problems here:

1. Permit users to customize the selection of microarchitectures (but I'd like to see a use case for that first)
2. Expose an explicit API that computes the best common target among a set of possible ones (basically hide the cycle above under a function call)

Let me know if the analysis here sounds incorrect or incomplete in any point.

**Comment by isuruf** [comment]
I can't remember the original intention of the issue, but the requirements have changed and I've captured that in #24 . Thanks a lot for the discussion.
