### ISSUE TITLE
Imprecise information returned from archspec.cpu.host() on Windows

### ISSUE THREAD

**Issue by markus-ferrell** [archspec/archspec#113]
On windows, archspec could return more significant info. It seems to provide default information that isn't detailed for the current system. My understanding is that there should be similar outputs for windows and WSL2 since they are on the same physical machine.

I ran this code through spack to test.

```
 >>> spack python
 >>> import archspec
 >>> archspec.cpu.host()
Microarchitecture('AMD64', [], 'generic', [], {}, 0)
```

On WSL2 for the same machine, `archspec.cpu.host()` returns much more significant info. 
```
 >>> bin/spack python
 >>> import archspec
 >>> archspec.cpu.host().family
Microarchitecture('x86_64', [], 'generic', set(), {'gcc': [{'versions': '4.2.0:', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}, {'versions': ':4.1.2', 'name': 'x86-64', 'flags': '-march={name} -mtune={name}'}], 'apple-clang': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name}'}], 'clang': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'aocc': [{'versions': '2.2:', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'intel': [{'versions': ':', 'name': 'pentium4', 'flags': '-march={name} -mtune=generic'}], 'oneapi': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'dpcpp': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'nvhpc': []}, 0)
```
For brevity, I showed the `archspec.cpu.host().family` output instead

**Comment by isuruf** [comment]
#114 gives more information, but not enough to figure out the microarchitecture. I suggest using https://github.com/workhorsy/py-cpuinfo to get these values. It's a pure python package that we can have as a dependency on windows.
