### ISSUE TITLE
Reconstructing the object from dict?

### ISSUE THREAD

**Issue by ickc** [archspec/archspec#139]
Let's say I get the host and convert it to dict:

```py
>>> archspec.cpu.host().to_dict()
{'name': 'broadwell',
 'vendor': 'GenuineIntel',
 'features': ['adx',
  'aes',
  'avx',
  'avx2',
  'bmi1',
  'bmi2',
  'f16c',
  'fma',
  'mmx',
  'movbe',
  'pclmulqdq',
  'popcnt',
  'rdrand',
  'rdseed',
  'sse',
  'sse2',
  'sse4_1',
  'sse4_2',
  'ssse3'],
 'generation': 0,
 'parents': ['haswell']}
```

And save this dict somewhere. Can I reconstruct the object on another host? It seems I can't use `archspec.cpu.microarchitecture.Microarchitecture` to do this currently. Are there any other ways?

Thanks.

**Comment by alalazo** [comment]
You are correct that we don't have a reverse operation. I'll add that.

> Can I reconstruct the object on another host?

I just want to mention that, to reconstruct a known host (e.g. a host that is in `microarchitectures.json`) you just need its name:
```python
>>> archspec.cpu.TARGETS["haswell"]
```

**Comment by ickc** [comment]
Thanks, @alalazo. May I ask what's the typical cadence of having a new release? Thanks.
