### ISSUE TITLE
Total ordering for x86

### ISSUE THREAD

**Issue by isuruf** [archspec/archspec#24]
I'm trying to use this for conda package manager (see https://github.com/conda/conda/pull/9930). The solver in conda will know the current architecture and it'll have to select the best available binary and it'll be easier if there was a total ordering. (If the current architecture is say value `5`, then add a condition that the binaries tagged value `<=5` and maximize this value.)

Clang and gcc have their own schemes. From https://github.com/archspec/archspec/issues/11

> For clang, they use a bit mask depending on the flags enabled. See https://reviews.llvm.org/D47474
GCC has a more complicated ordering based on the features enabled and the processor type, https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/i386-builtins.c#L1829-L1864

> We can add a field like,
"ordering": {
   "gcc": value,
   "clang": value,
   "spack": value,
}
for the 3 different schemes and the user will be able to use whichever ordering scheme they like.

**Comment by alalazo** [comment]
Apologies for the very late reply, I'm going through open issues to check what can be solved. What is wrong with the current ordering:
```python
>>> for s in archspec.cpu.TARGETS['icelake'].ancestors:
...     print(s)
... 
cascadelake
cannonlake
skylake_avx512
skylake
x86_64_v4
broadwell
haswell
ivybridge
x86_64_v3
sandybridge
westmere
nehalem
core2
x86_64_v2
nocona
x86_64
```
?

**Comment by tgamblin** [comment]
Note that there actually *is* no total ordering -- it's a DAG, which is a partial order, but I like Max's suggestion.

Question: Suppose you had an `icelake` system but `archspec` doesn't know `Icelake`. Would you rather it identify as `cascadelake` or `cannonlake`?  Why?

This is a place where we really don't know which to pick from DAG structure -- one doesn't clearly dominate the other -- they have divergent instructions.

**Comment by alalazo** [comment]
@isuruf Closing this issue since It seems answered to me, but feel free to reopen it if you think there are still actions to be taken. Thanks for the report and again sorry for the late reply.
