### ISSUE TITLE
Link to documentation in the front page of the project

### ISSUE THREAD

**Issue by vkarak** [archspec/archspec#44]
It'd be nice if you had a link to the documentation (https://archspec.readthedocs.io/) in the README page.

**Comment by alalazo** [comment]
![Screenshot from 2021-05-20 21-16-21](https://user-images.githubusercontent.com/4199709/119036102-a9422880-b9b0-11eb-85d0-d0710d8c19a5.png)

Added a link to the documentation in the "About" section. Thanks for reporting!
