### ISSUE TITLE
/sys/devices/cpu/caps/pmu_name

### ISSUE THREAD

**Issue by boegel** [archspec/archspec#5]
Just learned about this today...

```
$ grep "model name" /proc/cpuinfo | head -1
model name	: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz

$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

$ cat /sys/devices/cpu/caps/pmu_name
broadwell
```

Other system (CentOS 7.7, Intel Xeon Gold 6140)
```
 $ cat /sys/devices/cpu/caps/pmu_name
skylake
```

So, are we re-inventing the wheel?

**Comment by alalazo** [comment]
> So, are we re-inventing the wheel?

What do you mean?

**Comment by boegel** [comment]
> > So, are we re-inventing the wheel?
> 
> What do you mean?

Well, apparently a sufficiently recent Linux kernel also knows the μarch code name...

It doesn't seem to be correct though, @omula mentioned that he was getting `skylake` on a Cascade Lake system.
And it gets worse: https://github.com/torvalds/linux/blob/master/arch/x86/events/intel/core.c#L5005

`archspec` does more than just name stuff though, of course...

**Comment by alalazo** [comment]
> archspec does more than just name stuff though, of course...

Yeah, that would be my point. It aggregates knowledge for different hosts in the same place, adds logic to compare uarchs and query them for capabilities, adds information on compiler flags used to optimize for the microarchitecture.

**Comment by boegel** [comment]
OK, I'm fine to close this then. It's just good to have it on record that we know about `/sys/devices/cpu/caps/pmu_name`...

**Comment by tgamblin** [comment]
Also pmu_name doesn’t exist everywhere. Is there an equivalent for macs?  archspec is more fundamental; if you can query features,  you can reason about compatibility.
