### ISSUE TITLE
Apple M1 Pro support

### ISSUE THREAD

**Issue by adamjstewart** [archspec/archspec#83]
I'm testing out Spack on macOS 12.3.1 on the new Apple M1 Pro and I'm seeing a few error messages and an incorrect architecture determination:
```console
$ spack arch
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
darwin-monterey-x86_64
```
This is also true with https://github.com/spack/spack/pull/30683 which updates to the latest version of archspec. Is there anything I can do to help get M1 Pro support? Here is the output of `sysctl -a`: [m1-pro.txt](https://github.com/archspec/archspec/files/8703852/m1-pro.txt).

**Comment by alalazo** [comment]
What you report is that `archspec` is taking this branch in detection:

https://github.com/archspec/archspec/blob/1d616ad3dcd27e8a90cd5f4c8914ee233a186b0c/archspec/cpu/detect.py#L101-L116

which means the Python interpreter you are using reports `platform.machine` as `x86_64`. Can you confirm that:
```python
>>> import platform
>>> platform.machine()
'x86_64'
>>> 
```
?

**Comment by adamjstewart** [comment]
Yes, that's correct. It looks like the first Python in my path is from Homebrew. I'm guessing it's one of those universal binaries?
```console
$ python -c 'import platform; print(platform.machine())'
x86_64
$ file /opt/homebrew/bin/python
/opt/homebrew/bin/python: Mach-O 64-bit executable x86_64
```

I tried using `/usr/bin/python3` but XCode is still in the process of downloading so it doesn't work yet. I'll see if that Python works any better.

Not really sure what to do if we can't even trust Python to report the correct platform. But I guess that's the point of archspec, to figure that out based on the hardware itself?

**Comment by alalazo** [comment]
> Not really sure what to do if we can't even trust Python to report the correct platform. But I guess that's the point of archspec, to figure that out based on the hardware itself?

That's one of the points, yes. Up to now we trusted Python to report the correct architecture, but if that's not a valid assumption on M1 I think the case is mainstream enough to change how we detect things on Darwin.

**Comment by alalazo** [comment]
Can you check if this works https://github.com/archspec/archspec/pull/77/files ? If so I can simplify the implementation (remove the conditional and avoid checks on `platform.machine()`) and take care of both issues.

**Comment by alalazo** [comment]
For further reference: https://bugs.python.org/issue42704

**Comment by adamjstewart** [comment]
#77 works in the sense that I no longer see any sysctl error message, but `spack arch` still reports as x86_64.

FWIW, the Homebrew versions of Python are 2.7.10 and 3.7.5, both of which report x86_64.

**Comment by adamjstewart** [comment]
> I tried using `/usr/bin/python3` but XCode is still in the process of downloading so it doesn't work yet. I'll see if that Python works any better.

XCode finally installed! Looks like the system Python works just fine:
```console
$ /usr/bin/python3 -c 'import platform; print(platform.machine())'
arm64
$ spack arch
darwin-monterey-m1
```
Not sure if we should be making any distinction between M1 and M1 Pro or not, or if archspec actually knows the correct flags to optimize on M1. I guess the optimization flags don't really matter anyway since Spack can't yet use them for mixed compilers.

Should we close this as a duplicate of #76 or is there anything else that might be different about M1 Pro than M1?

**Comment by alalazo** [comment]
No, leave it open, I'm working on a fix will ping you when it's ready.
